# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/OExp02-IP2SOC/A7.xdc

# IP: ip/Seg7_Dev_0/Seg7_Dev_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Seg7_Dev_0 || ORIG_REF_NAME==Seg7_Dev_0} -quiet] -quiet

# IP: ip/ROM_1/ROM_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==ROM_1 || ORIG_REF_NAME==ROM_1} -quiet] -quiet

# IP: ip/RAM_1/RAM_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==RAM_1 || ORIG_REF_NAME==RAM_1} -quiet] -quiet

# XDC: d:/CS/ZJU_CO/OExp02-IP2SOC/OExp02-IP2SOC.gen/sources_1/ip/ROM_1/ROM_1_ooc.xdc

# XDC: d:/CS/ZJU_CO/OExp02-IP2SOC/OExp02-IP2SOC.gen/sources_1/ip/RAM_1/RAM_1_ooc.xdc
